# Generated by Django 3.1.2 on 2020-10-22 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='profile',
            new_name='created_by',
        ),
    ]
