# Generated by Django 3.1.2 on 2020-10-22 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20201022_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='archived',
            new_name='active',
        ),
    ]
