# Generated by Django 3.1.2 on 2020-10-22 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20201022_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='amount_of_questions',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)]),
        ),
    ]
