# Generated by Django 3.1.1 on 2020-09-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_current_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_save',
        ),
    ]
